export const STUDY = "STUDY"
export const CLEAR_STUDY = "CLEAR_STUDY"
export const PROFILE = "PROFILE"
export const CLEAR_PROFILE = "CLEAR_PROFILE"
export const JOBS = "JOBS"
export const CLEAR_JOBS = "CLEAR_JOBS"
export const CUSTOM = "CUSTOM"
export const CLEAR_CUSTOM = "CLEAR_CUSTOM"
export const PROJECTS = "PROJECTS"
export const CLEAR_PROJECTS = "CLEAR_PROJECTS"
export const COUNT = "COUNT" 
export const JOBS_COUNT = "JOBS_COUNT" 
export const CUSTOM_COUNT = "CUSTOM_COUNT" 
export const PROJECTS_COUNT = "PROJECTS_COUNT" 

